/**
 * Generates the two files that tell crawlers what exists, straight from the
 * app's own data so neither can drift from the routes that really work:
 *
 *   public/robots.txt   allow everything, point at the sitemap
 *   public/sitemap.xml  one <url> per route, plus one per publishable project
 *
 * Both are written into public/ so Vite copies them into dist/ with the rest
 * of the static files. Wired as `prebuild`, so `npm run build` always emits
 * them and they are gitignored rather than committed stale.
 *
 * Dependency-free by design: this is a build step, not a runtime one, and it
 * only needs node's own fs. Run it with `node scripts/generate-sitemap.mjs`.
 */

import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import { site } from "../src/data/site.js";
import { allProjects, publishedProjects, todoFields } from "../src/data/projects.js";

const here = dirname(fileURLToPath(import.meta.url));
const publicDir = join(here, "..", "public");

/** Strip the trailing slash so joins below never produce a double slash. */
const origin = site.siteUrl.replace(/\/+$/, "");

/* Static routes, in the order a crawler should reasonably meet them. */
const staticRoutes = [
  { path: "/", priority: "1.0", changefreq: "monthly" },
  { path: "/portfolio", priority: "0.9", changefreq: "monthly" },
  { path: "/contact", priority: "0.7", changefreq: "yearly" },
  { path: "/about", priority: "0.7", changefreq: "monthly" },
];

/* Case studies sit below the listing that links to them. */
const projectRoutes = publishedProjects({ prod: true }).map((project) => ({
  path: `/portfolio/${project.slug}`,
  priority: "0.6",
  changefreq: "yearly",
}));

const escape = (value) =>
  String(value)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&apos;");

const url = (route) =>
  [
    "    <url>",
    `      <loc>${escape(origin + route.path)}</loc>`,
    `      <changefreq>${route.changefreq}</changefreq>`,
    `      <priority>${route.priority}</priority>`,
    "    </url>",
  ].join("\n");

const sitemap = [
  '<?xml version="1.0" encoding="UTF-8"?>',
  "<!-- Generated by scripts/generate-sitemap.mjs. Do not edit by hand. -->",
  '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">',
  ...[...staticRoutes, ...projectRoutes].map(url),
  "</urlset>",
  "",
].join("\n");

const robots = [
  "# Generated by scripts/generate-sitemap.mjs. Do not edit by hand.",
  "User-agent: *",
  "Allow: /",
  "",
  `Sitemap: ${origin}/sitemap.xml`,
  "",
].join("\n");

mkdirSync(publicDir, { recursive: true });
writeFileSync(join(publicDir, "sitemap.xml"), sitemap);
writeFileSync(join(publicDir, "robots.txt"), robots);

const total = staticRoutes.length + projectRoutes.length;
console.log(
  `sitemap: ${total} urls (${staticRoutes.length} static, ${projectRoutes.length} projects) at ${origin}`,
);

/* Loud, and named: a TODO that survives into a build is unfinished copy
   someone meant to replace, and the only useful thing to say about it is
   which project and which field still needs writing. */
const drafts = allProjects
  .map((project) => ({ project, fields: todoFields(project) }))
  .filter(({ fields }) => fields.length > 0);

if (drafts.length) {
  console.warn("");
  console.warn(`WARNING: ${drafts.length} project(s) still contain TODO copy and are hidden from the public build:`);
  drafts.forEach(({ project, fields }) => {
    console.warn(`  /portfolio/${project.slug}  (${project.title})`);
    fields.forEach((field) => console.warn(`      ${field}`));
  });
  console.warn("");
}
